exp: resnet50_224_dog_c12
seed: 11785
use_amp: True
sync_bn: False
eval_metric: val_top1

data:
  root: /media/Bootes/dl_fgvc/
  name: dog
  image_size: 256
  input_size: 224
  batch_size: 16
  num_workers: 8

train:
  model_ema: False
  cutmix_minmax: None
  mixup: 0.0
  cutmix: 0.0
  smoothing: 0.0

optim:
  name: sgd
  lr: 0.03
  weight_decay: 0.0001
  sched: cosine
  epochs: 100
  warmup_epochs: 5

model:
  pretrained: 
    path: /home/dlfgvc/maituoy/11785-FGVC/best_checkpoints/model_best_c12.pth.tar
    pretrain: True
  backbone:
    name: resnet50_c12
    drop_path: 0.0
  head:
    num_classes: 120


